volumes:
  postgres_data:


services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    command: bash -c "alembic -c "./src/config/alembic.ini" upgrade head && python ./bot.py"
    container_name: teacher_bot

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres_bot
